--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VNDong/SkyWars-v2
branches:SkyWars_Svile_FixedbyItzElitePlayz.phar
- master
projects:
     SkyWars v2:
        path:SkyWars v2/
...

